---
- name: Ensures the project folder exists
  file:
    path: "{{ project_dir }}"
    state: directory

- name: Adding nginx conf file
  template:
    src: ../templates/nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ project_name }}.conf"

- name: Create the redis container
  docker_container:
    name: redis
    image: redis
    restart_policy: unless-stopped
    ports:
      - "6379:6379"
